AllSell_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users_allsell import views as user_views
from django.contrib.auth import views as auth_views
from products import views as product_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.registration, name='register_view'),
    path('profile/', user_views.profile, name='profile_view'),
    path('login/', auth_views.LoginView.as_view(template_name='users_allsell/login.html'), name='login_view'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users_allsell/logout.html'), name='logout_view'),
    path('', include('allsellapp.urls')),
    path('', include('products.urls')),
    path('', include('cart.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allsellapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from users_allsell import views as user_views
from products import views as product_views

urlpatterns = [
    # path('', views.home, name='home_view'),
    path('', views.HomeListView.as_view(template_name='allsellapp/home.html'), name='home_view'),


]

api/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('get-list', ProductsListView.as_view(), name="list_view"),
    path('post-list', ProductsCreateView.as_view(), name="post_view"),
    path('delete-list/<pk>', ProductsDestroyView.as_view(), name="delete_view"),
    path('update_item', UpdateItemView.as_view(), name="update_view"),
    path('validate_payment_amount', ValidatePaymentView.as_view(), name="validate_payment_amount_view"),
    path('process_payment', ProcessPaymentView.as_view(), name="process_payment_view"),
]

allsellapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from PIL import Image








class HomeBanner(models.Model):

    time_periods = [
        ('January', 'January_banners'),
        ('February', 'February_banners'),
        ('March', 'March_banners'),
        ('May', 'May_banners'),
        ('June', 'June_banners'),
        ('July', 'July_banners'),
        ('August', 'August_banners'),
        ('September', 'September_banners'),
        ('November', 'November_banners'),
        ('December', 'December_banners'),
    ]


    banner_title = models.CharField(max_length=40)
    banner_list_date = models.CharField(max_length=30, choices=time_periods, default="Test_period")

    def __str__(self):
        return f"Home Banner {self.banner_title}"




class BannerImgs(models.Model):
    product_img = models.ImageField(default='product_default.jpg', upload_to='product_pics')
    banner_item = models.ForeignKey(HomeBanner, null=True, blank=True, on_delete=models.CASCADE)
    

    def __str__(self):
        return f"Home Banner {self.product_img.file.name.split('/')[-1]}"

products/models.py
import uuid
import locale
from datetime import datetime
# Set the locale to English (United States)
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.utils.text import slugify
from djmoney.models.fields import MoneyField
from django.utils.timezone import make_aware
from django.core.exceptions import ValidationError

from PIL import Image

from .utils import get_currency_symbol
from .categories_and_colortags import categories, color_tags

class Address(models.Model):
    ADDRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'Shipping'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_first_name = models.CharField(default="First name", max_length=100)
    user_last_name = models.CharField(default="Last name", max_length=100)
    address_line_1 = models.CharField(max_length=200)
    address_line_2 = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)

    def __str__(self):
        return f"{self.address_line_1}, {self.address_line_2}, {self.city}, {self.zip_code}"

    class Meta:
        verbose_name_plural = 'Addresses'




class ProductCategory(models.Model):

    category = models.CharField(max_length=225, choices=categories, default='Category_test')
    color_tag = models.CharField(max_length=225, choices=color_tags, default='color_test')
    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.category

    # def get_absolute_url(self):
    #     return reverse('category_detail', kwargs={'slug': self.slug})



class ProductModel(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    slug = models.SlugField(unique=True, blank=True, default=None)
    product_name = models.CharField(max_length=40)
    product_description = models.TextField(max_length=500)
    product_price = MoneyField(max_digits=14, default=0.00, decimal_places=2, default_currency='USD')
    product_discount = models.IntegerField(default=0, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ForeignKey(ProductCategory, related_name='Category', blank=True, null=True, default=None, on_delete=models.CASCADE) #this
    stock = models.IntegerField(default=1)


    def __str__(self):
        return f'{self.product_name}'

    @property
    def in_stock(self):
        return self.stock > 0

    @property
    def discount_price(self):
        if self.product_discount:
            discount = self.product_price * (self.product_discount / 100)
            discount_price =  self.product_price - discount
            decimal_point_index = str(discount_price).find('.')
            
            decimal_places_count = len(str(discount_price)) - decimal_point_index - 1
            
            if decimal_places_count >= 3:
                discount_price = round(discount_price, 2)
            return discount_price


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name)
        return super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("product_view", kwargs={
            'slug': self.slug
        })



class ProductImg(models.Model):
    product_img = models.ImageField(default='product_default.jpg', upload_to='product_pics')
    is_carousel_active = models.CharField(max_length=10, null=True, blank=True)
    product = models.ForeignKey(ProductModel, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product}'


    def save(self, *args, **kwargs):
        product_img_length = ProductImg.objects.filter(product=self.product).count()
        if product_img_length < 1:
            self.is_carousel_active = "active"
        else:
            self.is_carousel_active = "not_active"
        return super().save(*args, **kwargs)






class Customer(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.email}'

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name

    @property
    def email(self):
        return self.user.email

    @property
    def get_customer_order(self):
        return self.order_set.get(customer=self, completed=False).get_cart_amount_of_items


class Order(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    customer = models.ForeignKey(Customer, blank=True, null=True, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    completed_date = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField(default=False)

    billing_address = models.ForeignKey(Address, related_name='billing_address', blank=True, null=True, on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(Address, related_name='shipping_address', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.reference_number


    def get_absolute_url(self):
        return reverse("order_details_view", kwargs={"pk": str(self.id)}) 


    @property
    def reference_number(self):
        return f"ORDER-{self.id}"

    @property
    def get_cart_total(self):
        orderproducts = self.orderproduct_set.all()
        total = sum([locale.atof(product.total_amount[1:]) for product in orderproducts])
        if orderproducts.first() == None and total == 0:
            return ""
        currency = str(orderproducts.first().total_amount)[0]
        return currency + f'{total:,.2f}'

    
    @property
    def get_cart_items(self):
        orderproducts = self.orderproduct_set.all()
        cart_items = [ item.product.product_name for item in orderproducts ]
        cart_items = ', '.join(cart_items)
        return cart_items

    @property
    def get_cart_total_as_float(self):
        orderproducts = self.orderproduct_set.all()
        total = sum([locale.atof(product.total_amount[1:])  for product in orderproducts ])
        return total


    @property
    def get_cart_amount_of_items(self):
        orderproducts = self.orderproduct_set.all()
        total = sum([order_product.quantity for order_product in orderproducts])
        return total


class OrderProduct(models.Model):
    product = models.ForeignKey(ProductModel, blank=True, null=True, on_delete=models.SET_NULL)
    order = models.ForeignKey(Order, blank=True, null=True, on_delete=models.SET_NULL)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.product.product_name



    @property
    def is_amount_in_stock(self):
        return self.quantity < self.product.stock

    @property
    def amount_in_stock(self):
        return self.product.stock

    @property
    def total_amount_without_discount(self):
        return str(self.product.product_price * self.quantity)

    @property
    def total_amount(self):
        if self.product.discount_price:
            total = self.product.discount_price * self.quantity
        else:
            total = self.product.product_price * self.quantity
        return get_currency_symbol(total.currency.code) + f'{total.amount:,.2f}'
        

allsellapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from users_allsell.models import Profile




class UserRegistrationForm(UserCreationForm):
        email = forms.EmailField()
        first_name = forms.CharField(max_length=30, required=False)
        last_name = forms.CharField(max_length=30, required=False)

        class Meta:
                #'model' Dictates where to save the form fields above. In this case, it is saved in registration_model db
                model = User
                #'fields' specifies the fields that are in the object
                fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']





class UserUpdateForm(forms.ModelForm):
        email = forms.EmailField()
        first_name = forms.CharField(max_length=30, required=False)
        last_name = forms.CharField(max_length=30, required=False)

        class Meta:
                model = User
                fields = ['first_name', 'last_name', 'username', 'email']

class ProfileUpdateForm(forms.ModelForm):
        class Meta:
                model = Profile
                fields = ['img']

allsellapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, TemplateView

from products.models import ProductModel, Order, ProductImg
from allsellapp.models import HomeBanner




class HomeListView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = ProductModel.objects.all()
        context['banners'] = HomeBanner.objects.all().filter(banner_title='test 1').first()

        return context

allsellapp/templates/allsellapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital@1&family=Montserrat:wght@700&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script type="text/javascript">
    var user = '{{request.user}}'
    function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
    {% if title %}
        <title>AllSell - {{ title }}</title>
    {% else %}
        <title>AllSell</title>
    {% endif %}
    
</head>
<body>
    <section id='nav-section'>
        <nav id='nav-bar'>
            <a href="{% url 'home_view' %}"><img src="{% static 'svgs/logo_transparent.svg' %}" alt=""></a>
            <div id='search-bar-container'>
                <input class='search-bar' placeholder="Search for products, brands, and more..." type="text" autofocus='' autocomplete="off">
                <button class='search-bar-send-btn' type='submit'>
                    <svg class='search-bar-send-icon' xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50">
                        <path d="M 21 3 C 11.621094 3 4 10.621094 4 20 C 4 29.378906 11.621094 37 21 37 C 24.710938 37 28.140625 35.804688 30.9375 33.78125 L 44.09375 46.90625 L 46.90625 44.09375 L 33.90625 31.0625 C 36.460938 28.085938 38 24.222656 38 20 C 38 10.621094 30.378906 3 21 3 Z M 21 5 C 29.296875 5 36 11.703125 36 20 C 36 28.296875 29.296875 35 21 35 C 12.703125 35 6 28.296875 6 20 C 6 11.703125 12.703125 5 21 5 Z"/></svg>
                </button>
            </div>
            <ul class='nav-bar-login'>
                {% if user.is_authenticated %}
                <div class='profile-link-container'>
                    <a class='profile-link' href="#">
                        <svg class='profile-icon' width="46" height="40" inkscape:version="0.92.5 (2060ec1f9f, 2020-04-08)" sodipodi:docname="profile_icon_item.svg" version="1.1" viewBox="0 0 13.229 13.229" xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <defs>
                                <linearGradient id="linearGradient2586" inkscape:collect="always">
                                <stop style="stop-color:#34d034" offset="0"/>
                                <stop style="stop-color:#1e90ff" offset="1"/>
                                </linearGradient>
                                <linearGradient id="linearGradient1386" x1="2.1076" x2="10.89" y1="-2.351" y2="-12.967" gradientUnits="userSpaceOnUse" inkscape:collect="always" xlink:href="#linearGradient2586"/>
                                <linearGradient id="linearGradient1388" x1="4.6274" x2="7.1558" y1="3.2326" y2="11.943" gradientUnits="userSpaceOnUse" inkscape:collect="always" xlink:href="#linearGradient2586"/>
                            </defs>
                            <sodipodi:namedview id="base" bordercolor="#666666" borderlayer="true" borderopacity="1.0" inkscape:current-layer="layer2" inkscape:cx="-0.86226742" inkscape:cy="67.849102" inkscape:document-units="mm" inkscape:pageopacity="0.0" inkscape:pageshadow="2" inkscape:showpageshadow="false" inkscape:window-height="704" inkscape:window-maximized="1" inkscape:window-width="1294" inkscape:window-x="72" inkscape:window-y="27" inkscape:zoom="2" pagecolor="#ffffff" showgrid="false" units="px"/>
                            <g inkscape:groupmode="layer" inkscape:label="Layer 2">
                                <path d="m-426.36 354.92c247.95-21.167 208.64-15.119 208.64-15.119l-36.286 78.619-169.33-12.095z" style="fill:none;stroke-width:.26458px;stroke:#000" inkscape:connector-curvature="0"/>
                                <path transform="scale(1,-1)" d="m12.328-6.7069a5.6174 5.6174 0 0 1-5.4255 5.803 5.6174 5.6174 0 0 1-5.803-5.4255 5.6174 5.6174 0 0 1 5.4255-5.803 5.6174 5.6174 0 0 1 5.803 5.4255" style="fill:none;paint-order:fill markers stroke;stroke-width:1.486;stroke:url(#linearGradient1386)"/>
                            </g>
                            <g inkscape:groupmode="layer" inkscape:label="Layer 3">
                                <g transform="matrix(1.2188 0 0 1.2188 -.68209 -1.2405)" style="fill:none;stroke:url(#linearGradient1388)">
                                <path d="m3.521 10.028c-0.022248-0.055624 0.10012-1.8857 1.5575-2.186 0 0 0.92065 0.84277 2.2107 0.00107 0 0 1.433 0.70845 1.3218 2.2882" style="fill:none;stroke-width:.33354;stroke:url(#linearGradient1388)" inkscape:connector-curvature="0" sodipodi:nodetypes="cccc"/>
                                <path d="m7.8143 5.2153a1.7365 1.8545 0 0 1-1.7365 1.8545 1.7365 1.8545 0 0 1-1.7365-1.8545 1.7365 1.8545 0 0 1 1.7365-1.8545 1.7365 1.8545 0 0 1 1.7365 1.8545z" style="fill:none;paint-order:fill markers stroke;stroke-width:.40042;stroke:url(#linearGradient1388)" inkscape:connector-curvature="0"/>
                                </g>
                            </g>
                        </svg>
                        <div class='profile-link-text-container'>
                            <p style="margin-bottom: 0;">Profile</p>
                            <svg class='dropdown-arrow' inkscape:version="0.92.5 (2060ec1f9f, 2020-04-08)" sodipodi:docname="dropdown.svg" version="1.1" viewBox="0 0 13.229 13.229" xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd">
                                <sodipodi:namedview id="base" bordercolor="#666666" borderopacity="1.0" inkscape:current-layer="layer1" inkscape:cx="48.375006" inkscape:cy="29.557539" inkscape:document-units="mm" inkscape:pageopacity="0.0" inkscape:pageshadow="2" inkscape:showpageshadow="false" inkscape:window-height="704" inkscape:window-maximized="1" inkscape:window-width="1294" inkscape:window-x="72" inkscape:window-y="27" inkscape:zoom="5.6" pagecolor="#ffffff" showgrid="false" units="px"/>
                                <g transform="translate(0 -283.77)" inkscape:groupmode="layer" inkscape:label="Layer 1">
                                    <g transform="matrix(1.1111 0 0 1.1111 -1.4841 -31.541)" style="stroke-width:.52917">
                                    <path class='dropdown-line-color' d="m2.1047 287.68 5.2619 5.2619"  inkscape:connector-curvature="0"/>
                                    <path class='dropdown-line-color' d="m12.628 287.68-5.2619 5.2619"  inkscape:connector-curvature="0"/>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <div id='profile-dropdown-list-container' hidden>
                            <ul class='dropdown-list profile-dropdown'>
                                <div></div>
                                <a href="{% url 'profile_view' %}"><li>Profile info</li></a>
                                <!-- <a href="{% url 'sell_item_view' %}"><li>Sell</li></a> -->
                                <a href="{% url 'orders_completed_view' %}"><li>Orders</li></a>
                                <div></div>
                            </ul>
                        </div>
                    </a>
                </div>
                <div class='profile-link-text-container'>

                    <a id="cart" class="d-flex gap-1 w-100" href="{% url 'cart_view' %}" >  
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        
                        </svg> Cart <span class="badge cart-items rounded-pill bg-danger">{% if user.customer.get_customer_order != None%}{{user.customer.get_customer_order}}{% endif %}</span>
                    </a>
                </div>

                <form action="{% url 'logout_view' %}" method="post">
                    {% csrf_token %}
                    <button style="text-decoration: none; background: none; border: none;" type="submit">Log out</button>
                </form>
                    
                {% else %}
                    <a href="{% url 'register_view' %}">Register</a>
                    <a href="{% url 'login_view' %}">Log in</a>

                {% endif %}

            </ul>
        </nav>

        
        <!-- <nav id='nav-bar-dropdown'>
            <a href="#">Categories<svg class='dropdown-arrow' inkscape:version="0.92.5 (2060ec1f9f, 2020-04-08)" sodipodi:docname="dropdown.svg" version="1.1" viewBox="0 0 13.229 13.229" xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd">
                <sodipodi:namedview id="base" bordercolor="#666666" borderopacity="1.0" inkscape:current-layer="layer1" inkscape:cx="48.375006" inkscape:cy="29.557539" inkscape:document-units="mm" inkscape:pageopacity="0.0" inkscape:pageshadow="2" inkscape:showpageshadow="false" inkscape:window-height="704" inkscape:window-maximized="1" inkscape:window-width="1294" inkscape:window-x="72" inkscape:window-y="27" inkscape:zoom="5.6" pagecolor="#ffffff" showgrid="false" units="px"/>
                <g transform="translate(0 -283.77)" inkscape:groupmode="layer" inkscape:label="Layer 1">
                 <g transform="matrix(1.1111 0 0 1.1111 -1.4841 -31.541)" style="stroke-width:.52917">
                  <path class='dropdown-line-color' d="m2.1047 287.68 5.2619 5.2619"  inkscape:connector-curvature="0"/>
                  <path class='dropdown-line-color' d="m12.628 287.68-5.2619 5.2619"  inkscape:connector-curvature="0"/>
                 </g>
                </g>
               </svg>
               </a>
            
            <a href="#">Product</a>
            <a href="#">Models</a>
            <a href="#">Contact</a>
        </nav> -->
        <div id='category-dropdown-list-container' hidden>
            <ul class='dropdown-list'>
                <div></div>
                <a href="#"><li>Cars</li></a>
                <a href="#"><li>Technology</li></a>
                <a href="#"><li>Decoration</li></a>
                <div></div>
            </ul>
        </div>
    
    </section>
    {% if messages %}
        <div class='message-container'>
            {% for message in messages %}
                <div class="shadow-container message-box-container {% if 'success' in message.tags %}message-box-container-success{% elif 'error' in message.tags %}message-box-container-error{% endif %}">
                
                    <div class='message-content registration-message'>
                        {{ message }}
                    </div>

                </div>
            {% endfor %}
        </div>
    {% endif %}


    {% block content %} {% endblock content %}

    <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
    
</body>
</html>

allsellapp/templates/allsellapp/home.html
{% extends 'allsellapp/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}


<section id='banner-section'>
    <div id='banner-data'>

        <div class='banner-img-container'>
            <div class='banner-btn-container'>
                <div class='prev_button'>
                    <svg id="svg-arrow-container" width='50' height='20' data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 936 1682"><defs></defs>
                        <polyline class="arrow" points="841 1587 95 841 841 95"/></svg>
        
                </div>
            </div>
            <div class='banner-img-slide'>

                {% for banner in banners.bannerimgs_set.all %}
                    <div class='banner-img-flex-slide'>
                        <img src="{{ banner.product_img.url }}" alt="">

                    </div>
                {% endfor %}
            </div>

            <div class='banner-btn-container'>

                <div class='next_button'>
                    <svg version="1.1" id="svg-arrow-container" width='50' height='20' xmlns="http://www.w3.org/2000/svg" 
                    viewBox="0 0 936 1682"  xml:space="preserve">
            
                        <polyline class="arrow" points="95,95 841,841 95,1587 "/></svg>
                </div>
            
    
            </div>
        </div>

        

        <div class='dot-container'>
            <ul class="dots">
            {% with indicator_quantity=banners.bannerimgs_set.all|length %}
                {% with ''|center:indicator_quantity as range %}
                    {% for _ in range %}
                        <li class="dot" value="{{ forloop.counter|add:"-1" }}"></li>
                    {% endfor %}
                {% endwith %}
            {% endwith %}
            </ul>
        </div>
    </div>
    


</section>

<section id='products-list-section'>
    <h3 class='main-heading my-5'>This week's offers</h3>
    <div class='products-gridbox-container'>
        
        {% for product in products %}
        <div class='product-item position-relative product-shadow-container'>
            {% if product.discount_price %}
            <h4 class="position-absolute top-50 badge bg-secondary">{{product.product_discount}}% off</h4>
            {% endif %}
            <div class='product-item-img-container'>
                <img src="{{ product.productimg_set.first.product_img.url }}" alt="">
            </div>
            
            <div class='product-item-info-container'>
                <h4 class='main-heading product-item-title my-3'> {{ product.product_name }}</h4>
                <p class='sec-paragraph mx-4 product-description'> {{ product.product_description }}</p>
                {% if product.product_discount %}
                    <div class="d-flex flex-row ms-4">
                        <del class="fs-5">{{ product.product_price }}</del>
                        <span class="fs-4 d-flex flex-row ms-2 fw-bold product-item-price">{{ product.discount_price }}{{ product.currency }}</span>
                    </div>
                {% else %}
                    <span class="fs-4 d-flex flex-row ms-4 fw-bold product-item-price">{{ product.product_price }}{{ product.currency }}</span>
                {% endif %}
                <div class="d-flex gap-1 ms-4 mt-4">
                    {% if user.is_authenticated %}
                    <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-primary update-cart">Add to cart</button>
                    {% else %}
                    <a class="btn btn-outline-primary" href="{% url 'register_view' %}">Add to cart</a>
                    {% endif %}
                    <a class="btn btn-outline-dark" href="{{ product.get_absolute_url }}">View</a>
                </div>

            </div>

        </div>
        {% endfor %}

        
    </div>


</section>



{% endblock content %}